version: 2

models:
  - name: base_jaffle_shop__customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: base_jaffle_shop__deleted_customers
    description: This model cleans up order data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
